### ISSUE TITLE
[Bug] BeforeAll de jeuRouter-jouer.test.ts n'importe pas le bon fichier

### ISSUE THREAD

**Issue by JeremieBergeron** [yvanross/log210-laboratoire0#3]
Lorsque je run tout les tests via ``npm run test``, j'obtiens cette erreur-ci:
```
 FAIL  test/lab0/new-test/jouer-lab0.test.ts
  ● test/routes/jeuRouter-jouer.test.ts › should contain expect(response.body.resultat.v3).toBeWithin(1, 7)

    ENOENT: no such file or directory, open 'test\routes\jeuRouter-jouer.test.ts'

       6 | beforeAll(async () => {
       7 |   const filename = path.join('test', 'routes', 'jeuRouter-jouer.test.ts');
    >  8 |   content = readFileSync(filename, 'utf-8');
         |                         ^
       9 | });
      10 |
      11 | describe('test/routes/jeuRouter-jouer.test.ts', () => {

      at test/lab0/new-test/jouer-lab0.test.ts:8:25
      at test/lab0/new-test/jouer-lab0.test.ts:8:71
      at Object.<anonymous>.__awaiter (test/lab0/new-test/jouer-lab0.test.ts:4:12)
      at test/lab0/new-test/jouer-lab0.test.ts:6:22
```

**Pourquoi cela arrive-t-il ?**
Ceci arrive, car le bon chemin pour accéder à ce fichier est: ``test\squelette\routes\jeuRouter-jouer.test.ts``
Le chemin qui est présentement fourni est: ``test\routes\jeuRouter-jouer.test.ts``

**Fichier impacté:**
https://github.com/yvanross/log210-laboratoire0/blob/7855b3534a88d035e8e40e03d1782a678f9f2ba5/test/lab0/new-test/jouer-lab0.test.ts#L6-L9

**Comment by danickblouin** [comment]
Il y a le même problème pour le test `redemarrerJeu-lab0.test.ts`.
Remplacer
`const filename = path.join('test', 'routes', 'jeuRouter-redemarrerJeu-lab0.test.ts');`
pars
`const filename = path.join('test', 'lab0', 'routes', 'jeuRouter-redemarrerJeu-lab0.test.ts');`
